### ISSUE TITLE
npx ts-node myscript.ts fails with ENOENT

### ISSUE THREAD

**Issue by manwithafox** [folke/ultra-runner#35]
I have a script in my package.json like ```"doit" : "npx ts-node myscript.ts"```.
```ts-node@8.6.2``` is in my devDependencies and installed. 
```ts-node.cmd``` is in ```node_modules/.bin/ts-node.cmd``` (as well as bash and ps versions)
Running the package script with ```npm run doit``` works fine.
Running ```npx ultra doit``` fails with 
```
error error Command ts-node failed with Error: spawn ...\node_modules\.bin\ts-node ENOENT. Is the command on your path?
```
I'm on Windows 10.

**Comment by manwithafox** [comment]
Seems to be a general problem.
Same issue with e.g. eslint, rimraf etc. - also without npx (which btw is superfluous in above example)

**Comment by folke** [comment]
Unfortunately I don't have access to Windows, but am running Jest tests on Github Actions (win).

I think I know what is happening here.

Do all those commands under node_modules have a `.cmd` extension?

Is on Windows, running `node_modules/.bin/ts-node.cmd` the same as `node_modules/.bin/ts-node` without using the extension?

**Comment by folke** [comment]
Could you report what you get if you execute the following command in `bash`?

```bash
$ which npx
```

**Comment by manwithafox** [comment]
```npx``` is here on my machine: 
```
C:\Program Files\nodejs\npx.cmd
```

But as said, also without ```npx``` commands are failing.
 
As written in my original post, all commands in
```node_modules/.bin``` exist in 3 versions: 
- ```.cmd``` - this is the normal case if running in cmd.exe
- ```<no extension>``` - for users of bash under Windows e.g. git brings most Unix tools incl. bash
- ```.ps1``` - powershell, guess this is needed when running in powershell

There is an environment variable ```ComSpec``` which tells you under which shell you are running. In my case it is:
```
ComSpec=C:\WINDOWS\system32\cmd.exe
```

**Comment by manwithafox** [comment]
In ```bash``` (the one from WSL) there is no ```ComSpec``` env in my case. But I see
```
SHELL="/bin/bash"
```

In PowerShell I have the same ```ComSpec``` as in ```cmd.exe```. No real indication if running in PS. But I guess it should be possible to start the ```.cmd``` versions as well.

**Comment by folke** [comment]
Just installed Parallells desktop with Windows 10. Will look into this.

Thanks for the additional info!

**Comment by folke** [comment]
I just released a new version that fixes running on Windows. Let me know if you have any more issues!

**Comment by manwithafox** [comment]
Almost perfect.

It still stumbles over an ```nyc mocha``` call with same problems as above:

```
  × $ nyc mocha --config ./test/.mocharc.js 3.154s
    │ 'mocha' is not recognized as an internal or external command,
    │ operable program or batch file.
    │ events.js:288
    │       throw er; // Unhandled 'error' event
    │       ^
    │
    │ Error: spawn mocha ENOENT
    │     at notFoundError (C:\x\node_modules\foreground-child\node_modules\cross-spawn\lib\enoent.js:6:26)
    │     at verifyENOENT (C:\x\node_modules\foreground-child\node_modules\cross-spawn\lib\enoent.js:40:16)
    │     at ChildProcess.cp.emit (C:\x\node_modules\foreground-child\node_modules\cross-spawn\lib\enoent.js:27:25)
    │     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    │ Emitted 'error' event on ChildProcess instance at:
    │     at ChildProcess.cp.emit
    │ (C:\x\node_modules\foreground-child\node_modules\cross-spawn\lib\enoent.js:30:37)
    │     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
    │   code: 'ENOENT',
    │   errno: 'ENOENT',
    │   syscall: 'spawn mocha',
    │   path: 'mocha',
    │   spawnargs: [ '--config', './test/.mocharc.js' ]
    │ }
    │
error
error Command nyc failed with exit code 1

```

**Comment by folke** [comment]
Will look into this!

In your setup, I assume that:
* Istanbul has been installed globally?
* mocha in your local node modules?

Could you post back the results of

```shell
$ which nyc

$ which mocha
```

Whenever executing a command within a script hook, I assume `ultra` needs to add the local node modules .bin directory to the path of the child process.

**Comment by folke** [comment]
As a workaround, putting the following in your script would probably work:
```shell
nyc npx mocha --config ./test/.mocharc.js
```

Either way, I'll look into this tomorrow to have it fixed.

**Comment by manwithafox** [comment]
Both ```nyc``` and ```mocha``` are local `devDependencies`, not globally installed.
```instanbul``` is no direct dependency, some parts come via ```nyc```.

**Comment by folke** [comment]
Fixed in 2.3.4! 2cf5daaa193c366e7692d37e158ffae733186521

**Comment by manwithafox** [comment]
Works like a charm!
Thank you so much for the super quick fixes.

Kind regards

**Comment by folke** [comment]
You're welcome!

**Comment by manwithafox** [comment]
Oops, unfortunately I was too quick - had some compilation error and tests were not executed at all.
It still fails with 2.3.4. Output is the very same as above. So sorry...

**Comment by manwithafox** [comment]
```nyc npx mocha --config ./test/.mocharc.js``` works but is a lot slower, about 20%
Maybe because of the huge amounts of output that gets repainted?

**Comment by folke** [comment]
I only fixed the issue for Macos and Linux apparently.

The env vairable on Windows is `Path` instead of `PATH`. `path-key` fixes this cross-platform.

Just tested it all in Windows 10 (on Parallells) and it now correctly expands the path.

**Comment by folke** [comment]
Fixed in 2.3.5 2f6a9b52c1535c692b54b6d404e8e210c1b77237 🚀

**Comment by manwithafox** [comment]
Now it works 👍 
Thanks a lot
